### ISSUE TITLE
Use Node process?

### ISSUE THREAD

**Issue by bryanjos** [bryanjos/elixirscript#102]
If it's possible to introduce a port for calling to a node process during compilation it could open some doors for a better experience. In particular calling babel to turn the es6 code into whatever module system the user wants, and for using it's dead code elimination feature.

The problem is performance. In previous versions that called out to a node process, one of the demo projects took 20s to compile. Without node, it was down to ~200ms. A small performance hit would be fine and is expected.

**Comment by bryanjos** [comment]
I tried using node again, this time using exos. I now see that the main source of bottleneck was the json encoding because without using it, the the performance stayed almost the same. Where the tests would run in 0.1s without it, they ran in 0.2s with it.

**Comment by ryanstout** [comment]
@bryanjos sorry, I'm new to this project and was just curious, why not just go to es5 instead?  It's a bit more work on your end I guess, but seems like it will make debugging simpler when you go to add source maps. I think Babel can take in source maps to start, but then I think you'll still have the complexity of two compilers adding indirection. Anyway, again, I'm new to the project, so I'm just curious. Great work on everything!  Thanks.

**Comment by bryanjos** [comment]
@ryanstout that's a valid question and one I wonder about myself more and more :). The biggest reasons are that es6 have constants, symbols (which are used here for atoms), modules, iterators and destructuring. Generators may or may not also play a factor later when it comes to erlang-style processes.

I originally wanted babel for maybe the ability to use es7+ features that would make translation easier, dead code elimination, and for picking an alternative module system. I'm not sure any more if making babel a part of this is a way forward or not anymore. I'm also not sure how to include the needed node modules when Elixirscript is used as a dependency.

Saying all of that, I am open to any suggestions on how to improve the experience. It's been bugging me a lot lately. I know right now the code that is created still has to go through a transpilation step of some kind. I think that the only es6 feature that's being used here that's not in evergreen browsers currently are modules. But there are so many different kinds of module systems and build tools out there that I figured following the spec would be the easiest and most beneficial.

**Comment by ryanstout** [comment]
@bryanjos do you have a link to dead code elimination in babel? (I didn't see much when googling)  I didn't think that was possible in a language like javascript, other than just not including files based on requires.

**Comment by bryanjos** [comment]
It used to be on their plugins page under experimental, but since babel 6.0 was released I don't see it anymore. The only thing I see is this, https://github.com/achicu/babel-plugin-dead-code-elimination. Not sure if that's the plugin version of what was there before or not.

**Comment by bryanjos** [comment]
After thinking things over I do not think this will be needed.
