### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by bryanjos** [bryanjos/elixirscript#118]
It would be nice if these packages lived inside hex and were downloaded in the same way. In other words, these should be as close to the same format as elixir dependencies as possible. Pulling down elixirscript dependencies should work with `mix deps.get`

There would be some changes in the compiler as well. 

* Currently all output is placed in a flat directory structure. This would have to change to place each package/dependency's output in a subfolder (in case 2 dependencies have modules of the same name).

This
```
├── Elixir.App.js
├── Elixir.ElixirScript.Agent.js
├── Elixir.ElixirScript.Atom.js
├── Elixir.ElixirScript.Base.js
├── Elixir.ElixirScript.Bitwise.js
├── Elixir.ElixirScript.Collectable.js
├── Elixir.ElixirScript.Enumerable.js
├── Elixir.ElixirScript.Integer.js
├── Elixir.ElixirScript.JS.js
├── Elixir.ElixirScript.Kernel.js
├── Elixir.ElixirScript.Keyword.js
├── Elixir.ElixirScript.List.js
├── Elixir.ElixirScript.Macro.Env.js
├── Elixir.ElixirScript.Map.js
├── Elixir.ElixirScript.MapSet.js
├── Elixir.ElixirScript.Module.js
├── Elixir.ElixirScript.Range.js
├── Elixir.ElixirScript.String.Chars.DefImpl.Elixir.Atom.js
├── Elixir.ElixirScript.String.Chars.DefImpl.Elixir.BitString.js
├── Elixir.ElixirScript.String.Chars.DefImpl.Elixir.Float.js
├── Elixir.ElixirScript.String.Chars.DefImpl.Elixir.Integer.js
├── Elixir.ElixirScript.String.Chars.DefImpl.Elixir.L.Marker.js
├── Elixir.ElixirScript.String.Chars.DefImpl.Elixir.List.js
├── Elixir.ElixirScript.String.Chars.DefImpl.Elixir.Tuple.js
├── Elixir.ElixirScript.String.Chars.DefImpl.js
├── Elixir.ElixirScript.String.Chars.js
├── Elixir.ElixirScript.String.js
├── Elixir.ElixirScript.Tuple.js
├── Elixir.ElixirScript.View.js
└── Elixir.js
```

Would turn into

```
├── Elixir.js # core file. Don't know "right" place to put this in structure
├── adep # some dependency
├── app # your app
│   └── Elixir.App.js
└── stdlib
    ├── Elixir.ElixirScript.Agent.js
    ├── Elixir.ElixirScript.Atom.js
    ├── Elixir.ElixirScript.Base.js
    ├── Elixir.ElixirScript.Bitwise.js
    ├── Elixir.ElixirScript.Collectable.js
    ├── Elixir.ElixirScript.Enumerable.js
    ├── Elixir.ElixirScript.Integer.js
    ├── Elixir.ElixirScript.JS.js
    ├── Elixir.ElixirScript.Kernel.js
    ├── Elixir.ElixirScript.Keyword.js
    ├── Elixir.ElixirScript.List.js
    ├── Elixir.ElixirScript.Macro.Env.js
    ├── Elixir.ElixirScript.Map.js
    ├── Elixir.ElixirScript.MapSet.js
    ├── Elixir.ElixirScript.Module.js
    ├── Elixir.ElixirScript.Range.js
    ├── Elixir.ElixirScript.String.Chars.DefImpl.Elixir.Atom.js
    ├── Elixir.ElixirScript.String.Chars.DefImpl.Elixir.BitString.js
    ├── Elixir.ElixirScript.String.Chars.DefImpl.Elixir.Float.js
    ├── Elixir.ElixirScript.String.Chars.DefImpl.Elixir.Integer.js
    ├── Elixir.ElixirScript.String.Chars.DefImpl.Elixir.L.Marker.js
    ├── Elixir.ElixirScript.String.Chars.DefImpl.Elixir.List.js
    ├── Elixir.ElixirScript.String.Chars.DefImpl.Elixir.Tuple.js
    ├── Elixir.ElixirScript.String.Chars.DefImpl.js
    ├── Elixir.ElixirScript.String.Chars.js
    ├── Elixir.ElixirScript.String.js
    ├── Elixir.ElixirScript.Tuple.js
    └── Elixir.ElixirScript.View.js
```
 
* These dependencies, when downloaded, would have to be pulled from a location (_deps folder?). The compiler would have to know how to find `elixirscript` deps. 
* Dependency references to other dependencies would have to be resolved. When a reference to a dependency is called, the compiler would have to know which folder (named after the app/dep) the dependency's output would live in (i.e. if using Diff.Path, compiler would have to know that the path to Diff.Path in es2015 would be `../diff/Elixir.Diff.Path`)
* The compiler would have to know what the user's app is and what will be the entry point

Making the standard library into a dependency may help enough to resolve some of these issues.

**Comment by cjhowe** [comment]
Will this be integrated with Mix, like as a task or something?

**Comment by bryanjos** [comment]
@cjhowe I'm not sure yet. I haven't really thought that far into it. What would be nice is if these dependencies could live in hex. So when someone runs `mix deps.get`, it would download elixir,elixirscript and erlang dependencies all the same.

I'll update the task description and add more details

**Comment by bryanjos** [comment]
Actually I think I want to find out how clojure/clojurescript handles this

**Comment by bryanjos** [comment]
https://github.com/clojure/clojurescript/wiki/Dependencies

**Comment by bryanjos** [comment]
So I think some assumptions can be made here. If the assumption is that an elixirscript project is the same as an elixir project (made with `mix.new <project_name>`) or is part of an existing elixir project, it can be assumed that the project's dependencies are defined inside of the mix.exs file. With that, it can be assumed that the files for these dependencies are inside of the `deps` folder. 

With those set of assumptions, finding dependencies for compilation should be the process of digging through the deps folder, finding dependencies and building a dependency graph. If needed, a requirement of setting exactly which deps should be used with elixirscript via something inside of the mix.exs file can be used.

**Comment by bryanjos** [comment]
Using `Mix.Dep.loaded([env: "#{Mix.env}"])` to reduce the number of deps to look in would help

**Comment by bryanjos** [comment]
Work is being done on this in the `deps_compilation` branch https://github.com/bryanjos/elixirscript/tree/deps_compilation

I'm refactoring the compilation a bit, but in the end, at least compilation should look simpler

**Comment by bryanjos** [comment]
#206 will have some suport for this. In particular if a dep if defined to be allowed in the `elixirscript` env. Loads ex files, but only compiles exjs files.
