### ISSUE TITLE
Flatten output directory

### ISSUE THREAD

**Issue by bryanjos** [bryanjos/elixirscript#123]
Right now, the compiler will take the following module:

```elixir
defmodule A.B.C do
end
```

And output it in a JS file as so:

```
a/b/c.js
```

This change would make the output like so:

```
A.B.C.js
```

This would mimic the structure of beam files in the ebin directory in Elixir's _build folder. This should also remove the Inflex dependency as well.

**Comment by scrogson** [comment]
:+1:
