### ISSUE TITLE
Pattern matching for maps having atom keys

### ISSUE THREAD

**Issue by halohalospecial** [bryanjos/elixirscript#139]
Hi :)

Pattern matching for maps having string keys is working as expected:

  m1 = %{"abc" => 123}
  %{"abc" => v1} = m1
  :console.log(v1)
  # 123

But, it's not working for maps having atom keys:

  m2 = %{abc: 123}
  %{abc: v2} = m2
  :console.log(v2)
  # undefined

**Comment by bryanjos** [comment]
Thanks! I think it is in the javascript pattern matching library and hopefully should be a quick fix

**Comment by halohalospecial** [comment]
Hi again :)

I issued a pull request for this (https://github.com/bryanjos/elixirscript/pull/142).  Kindly review if you have time.  Thanks!

**Comment by bryanjos** [comment]
I just saw it and merged it. Thanks!
