### ISSUE TITLE
Unexpected Token : Elixir.ElixirScript.Html.js

### ISSUE THREAD

**Issue by scitesy** [bryanjos/elixirscript#148]
This could be a babel problem...not sure.

It looks like babel-brunch (5.1.2) fails to compile ElixirScript.Html.js at line 32:
...
    const external_resource = let [tags_path] = Elixir.Core.Patterns.match(Elixir.Core.Patterns.variable(),Path.join(Object.freeze(['.', 'tags.txt'])));;
...
The error from the Babel compiler is:
error: Compiling of 'web/static/js/Elixir.ElixirScript.Html.js' failed. web/static/js/Elixir.ElixirScript.Html.js: Unexpected token (32:30)

**Comment by bryanjos** [comment]
Thanks. I'm planning on taking time to make sure things work in various workflows this week so this is good information

**Comment by scitesy** [comment]
Thank you! I'm glad the timing is good.

**Comment by bryanjos** [comment]
This should be fixed now. That particular code is no longer part of the output.
