### ISSUE TITLE
Duplicate declaration "delete_at" : ElixirScript.Tuple.js

### ISSUE THREAD

**Issue by scitesy** [bryanjos/elixirscript#149]
Another issue with the Babel compilation of ElixirScript standard library output:
ElixirScript.Tuple.js Line 45:
...
    const delete_at = Elixir.Core.Patterns.defmatch(Elixir.Core.Patterns.make_case([Elixir.Core.Patterns.variable(), Elixir.Core.Patterns.variable()],function(tuple,index)    {
...
The error is:
Compiling of 'web/static/js/Elixir.ElixirScript.Tuple.js' failed. web/static/js/Elixir.ElixirScript.Tuple.js: Line 45: Duplicate declaration "delete_at"

This issue occurs during the Babel compilation phase after ElixirScript Brunch performs its compilation from Elixir to JavaScript in a Phoenix application.

**Comment by bryanjos** [comment]
This should be cleared up now in the latest version on master
