### ISSUE TITLE
Actors, Processes, etc

### ISSUE THREAD

**Issue by bryanjos** [bryanjos/elixirscript#15]
Always thought of web workers in part for this, but they don't exist in node.js. But there will be web workers in io.js https://github.com/iojs/io.js/issues/180. So if the plan stays the same and web workers are used, then actors will work at least on the web and in io.js for the time being.

**Comment by mgwidmann** [comment]
Only problem with the above thought is that web workers cannot access the DOM, window, or things like that. So if everything is a web worker (like everything is a process in Elixir), how are you supposed to interact with window or the DOM?

**Comment by bryanjos** [comment]
@mgwidmann That's a good point. Web workers may not work. Or they may still be an option but with that stipulation. 

I would be interested in hearing about any alternatives. I still have a while before I start any work on this and nothing is set in stone.

**Comment by bryanjos** [comment]
So accessing the actual DOM might be out of reach, but using a virtual DOM in web workers may be a way to go.

**Comment by bryanjos** [comment]
Closing this and going to open another issue that does not include web workers specifically
