### ISSUE TITLE
Add more friendly way to JS compatible maps

### ISSUE THREAD

**Issue by bryanjos** [bryanjos/elixirscript#157]
Currently, to have map keys use string instead of symbols in JavaScript objects, one has to do the following.

```elixir
%{ "key" => value }
```

This is a proposal to come up with a more natural way of defining a map that has string keys in JavaScript. The way proposed in #150 is:

```elixir
${ key: value }
```

Notice `%` is replaced with `$`. This does not have to be the final syntax if another option is better. If new syntax is added, it should be defined as a macro. Ideally converting the second code snippet into the first one.

**Comment by bryanjos** [comment]
@AdamBrodzinski I tried creating a macro for the expression `${ key: value }`, but I get compilation errors when quoting it "it complains about the $". I tried some other options like `obj(a: "b")` or `o(a: "b")` which work well. What do you think?

**Comment by bryanjos** [comment]
I currently have "Kernel.object" in master. From the changelog:

  Added `Kernel.object/1` function to make it more natural to create a JavaScript object with string keys
    Elixirscript, by default turns the following, `%{a: "b"}` into `{[Symbol.for("a")]: "b"}` in JavaScript. In order to get string keys,
    one would have to do `%{"a" => "b"}` which turns into `{a: "b"}` in JavaScript. With `Kernel.object`, you can create string keyed maps
    conveniently, `object(a: "b")` which turns into `{a: "b"}`.

 **NOTE**: when updating the created by, you still have to use the string form `%{ my_map | "a" => "c" }`

If there aren't any objections, we can go with this.

**Comment by AdamBrodzinski** [comment]
@bryanjos awesome! i'll check this out this week :smile:   I think `object(a: "b")` would be just fine! Typically that 'first' line is something like `styles = object(` anyway so the extra chars aren't a big deal IMHO and also make it more clear what it is were the proposed `${a: "b"}`  is not clear.

Great job! :beers:
