### ISSUE TITLE
Protocols: Dynamically load protocol implementation

### ISSUE THREAD

**Issue by bryanjos** [bryanjos/elixirscript#161]
Connected to #155 and #160. Update protocol to dynamically load implementation of protocol when type is encountered. If module for protocol does not exist, an error should be thrown. Once an implemention is loaded, it should be cached.

There are 2 complications with this. One, ES2015 imports can only be made at the top level scope. System.js is probably the only option if we are keeping ES2015 modules. Two, this needs to be synchronous. System.js should be able to handle it using `System.get`. `System.import` won't work because it returns a promise.

Alternatives to one and two are to switch to CommonJS modules. They are synchronous and can be called below the top scope. This would require some significant, but not complicated effort to change from ES2015 modules to CommonJS.

To give an example of what would happen:

```javascript
      return function(...args) {
        let thing = args[0];
        let fun = null;

        let protocolType = this.constructor;
        let ImplementationType = thing.constructor;

        try{
          let implementation = null;
          //Check in cache first
          if(this.cache.has(ImplementationType){
             implementation = this.cache.get(ImplementationType);
           }else{
             implementation = System.get(protocolType + "." + ImplementationType);
             // alternatively
             // implementation = require(protocolType + "." + ImplementationType);
           }

           return implementation[funName].apply(this, args);
        }catch(e){
          throw new Error("No implementation found for " + thing);
        }
      }
```

**Comment by togakangaroo** [comment]
The closest you will find to something that can handle this is the way requirejs works in commonjs mode.

It's not simple.

You need to

1) load the file as text using ajax
2) use regex to find any import of modules
3) pull all these in (recursively - since they might have modules of their own)
4) stick them in a module cache
5) rewrite the module import to pull from the module cache

You *might* just be able to use requirejs for this but I'm not sure whether it actually supports commonjs in nested scopes. Either way its certainly doable in principle.

**Comment by bryanjos** [comment]
Yeah falling back to commonjs/requirejs is starting to look better. Still would be nice to have an es6 solution. There won't be any situation where there are nested modules so that is ok. 

That does give me another idea. The loading can happen at the top level if there was a way to let it know which files or some wildcard way to get all files beginning with a prefix.

**Comment by togakangaroo** [comment]
If you say this requires a serverside tool to run (which you are since exjs is currently written in ex) you can at compile time generate a manifest of all js files and inject that into the output so that it knows all file paths available.

**Comment by bryanjos** [comment]
Yeah but then I thought about it that could still run into the top level scope issue. I may try to experiment with System.js. It would work but there is just so much to think about as far as configuration and if there is another version of it in use (i.e. jspm)

**Comment by bryanjos** [comment]
Change of plans. So what we can do is still make each implementation it's own module, but add a module that collects the implementation imports and during the compilation of the protocol, add an import to this module.

**Comment by bryanjos** [comment]
Protocols become modules and each implementation becomes a module. A protocol "manifest" is created after initial complilation to gather the implementations so that they can be used by the protocol. The protocol only imports the "manifest" to include the implementations. 

This should fulfill the goal of separating protocols from their implementations. This should also make it easier for caching. At most whenever an implementation is changed, n + 1 files will need to be updated (implementation module + "manifest").

Using `Blank` as an example

Protocol:
```javascript
//Elixir.Blank.js : Protocol
import Elixir$ElixirScript$Kernel from './Elixir.ElixirScript.Kernel';
import Implementations from './Elixir.Blank.defimpl';

const Elixir$Blank = Elixir.Core.Functions.defprotocol({
    blank__qmark__: function() {}
});

for ({ Type, Impl } of Implementations) {
    Elixir.Core.Functions.defimpl(Elixir$Blank, Type, Impl);
}

export default Elixir$Blank;
```

Protocol Implementation:
```javascript
//Elixir.Blank.Array.js
import Elixir$ElixirScript$Kernel from './Elixir.ElixirScript.Kernel';

export default {
    Type: Array,
    Implementation: {
        blank__qmark__: function() {.....
        }
    }
}
```

Protocol Manifest:
```javascript
//Elixir.Blank.defimpl.js
import Elixir$ElixirScript$Kernel from './Elixir.ElixirScript.Kernel';
import { ArrayType, ArrayImplementation } from './Elixir.Blank.Array';
//.. more implementation imports
let impls = [];
impls.push[{
    Type: ArrayType,
    Implementation: ArrayImplementation
}];

export default impls;
```

**Comment by bryanjos** [comment]
I should elaborate a bit. The *.defimpl.js file would be created with the protocol, but it would be populated in a stage afterwards that takes that, looks for the implementation files, and builds it up using that.
