### ISSUE TITLE
Allow for arbitrary placement of Elixir.js library file

### ISSUE THREAD

**Issue by cjhowe** [bryanjos/elixirscript#167]
For the sanity of package maintenance, it's usually good to be able to specify some type of prefix where files to be distributed files should go. This would require files underneath the prefix to follow the standard Unix file layout, with the `bin` and `lib` directories. Currently, the `Elixir.js` standard library file will either be searched for in the build path or the directory above the `elixirscript` file. This doesn't really work for a Unix file layout, where `Elixir.js` would be in the `lib` folder. The current way to work around this is to put the whole `dist` directory structure into some location, for example the `lib` directory, and symlink to the executable from the `bin` directory. See my [Arch Linux PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=elixirscript) for an example of how that looks.

It'd be a lot better if we could solve this with a compile time flag that specifies a sort of "prefix" or "library" directory where the Elixir.js file will be stored when distributed. Another option is an environment variable, which wouldn't help much for package maintainers since they can't set persistent environment variables easily. Finally, we could have a config file containing this directory, although the location of that config file would also become a problem.

I think the best way to proceed is a compile time flag, but if anyone has a more idiomatic approach, it'd be good to hear all of the options.

**Comment by bryanjos** [comment]
One way to handle it might be to have a config file that is read from at compile time as an external reference with the prefix. The dist mix task could take a prefix option, add or create a config file with the prefix and then force compilation which would read from the file and populate some prefix module attribute with the value.

**Comment by bryanjos** [comment]
Actually maybe the standard elixir config files could help with this

**Comment by bryanjos** [comment]
Yeah I'm going to try adding a config block to the config file with a prefix value. If it's set to nil then it will work as it does currently. If the value is a binary that points to a path, it will use the path to look for the javascript files.

**Comment by bryanjos** [comment]
I still have to test and document, but the feature is in master currently. It's been a busy week but hopefully I can get that done soon enough

**Comment by bryanjos** [comment]
The readme has been updated on information on how to update the lib_path to point to a different location.

**Comment by cjhowe** [comment]
:+1:
