### ISSUE TITLE
Can I copy your contributing.md file?

### ISSUE THREAD

**Issue by dirkrombauts** [bryanjos/elixirscript#176]
Hi,

I'm the maintainer of [Pickles](http://www.picklesdoc.com/), and a friend showed me your Contributing.md file yesterday as an example of a very good Contributing.md file. I read it through and I agree that it is very informative and clear.

I would like to use it to enhance the Contributing.md of Pickles - is that alright with you?

**Comment by bryanjos** [comment]
Sure! I actually borrowed a lot of it from [Elixir's](https://github.com/elixir-lang/elixir) Contributing.md which is looks like they merged into the readme at some point

**Comment by bryanjos** [comment]
Also, very cool project!

**Comment by dirkrombauts** [comment]
Thanks!
