### ISSUE TITLE
How do you interop with asynchronous javascript ?

### ISSUE THREAD

**Issue by kwijibo** [bryanjos/elixirscript#212]
Hi,

Sorry if this should be obvious, but I was just reading through https://bryanjos.gitbooks.io/elixirscript-book/ and I couldn't see how to write Elixirscript code that calls javascript functions that accept callbacks, or return Promises.

**Comment by bryanjos** [comment]
Hi,

Sorry I need to add more examples. So to call asynchronous code is mostly the same as with Javascript as in you can either use an anonymous function or a captured function. Below is an example using the fetch api to show using with a promise.

```elixir
:window.fetch("/my/json/api")
.then(fn(response) -> response.json() end)
.then(fn(json) -> :console.log(json) end)
```

For a callback, not much different

```elixir
file.read("file.json", fn
  (nil, data) ->
    :console.log(data)
  (err, _) ->
    :console.error(err)
end) 

```

I used the last example to show that `fn` in elixirscript allows for multiple clauses just as in Elixir.

**Comment by kwijibo** [comment]
Thanks a lot, that's great. I didn't realise you could use the returned javascript objects like `Promise` and `Response` directly in elixirscript

**Comment by bryanjos** [comment]
No problem. The only thing I can think of that is a problem would be creating JavaScript classes in Elixirscript. There isn't a way to do that now. You can instantiate classes with `JS.new` though so you can still use them.
