### ISSUE TITLE
Add way to update mutable JavaScript items

### ISSUE THREAD

**Issue by bryanjos** [bryanjos/elixirscript#50]
This would be useful for times when one needs to actually update an existing JavaScript variable. Already implemented a module named Mutable with a function named update, but maybe if it's just one function it can be placed in another module.

**Comment by OpakAlex** [comment]
You think it's good idea update mutable items? 
I think more powerfull do't use mutable structures.

**Comment by bryanjos** [comment]
Its more for interacting with existing js libraries that may not play well with immutability. Everything right now is immutable. The goal would be for it to be something explicit and not convenient so that it's only used when absolutely needed.

**Comment by OpakAlex** [comment]
yes...but i afraid, because one reason for use elixirscript it's all is immutability. And people can use this is js...

**Comment by bryanjos** [comment]
I'm still hoping for some more feedback. There may be a better way to handle it. Or it may not be needed at all but its something I ran into while doing the last sample project I made

**Comment by grabbou** [comment]
I would suggest bundling `Immutable.js` as a default dependency to handle these cases in order to avoid reinventing the wheel yet keeping relatively similar data flow.

**Comment by bryanjos** [comment]
I've thought about adding Immutable.js, but haven't settled on it for some reasons I still have to figure out. It also wouldn't resolve the issue here. The problem is that currently ElixirScript works just like Elixir in that you can reuse the same name, they don't point to the same place in memory. For instance in Elixir you can do this:

```Elixir
a = 1
a = 2
```

Behind the scenes 2 separate variables are created:

```Elixir
a0 = 1
a1 = 2
```

I do the same thing in ElixirScript. The first example is converted to this:

```JavaScript
let a0 = 1;
let a1 = 2;
```

If at some point when interacting with a JavaScript library that needs to have a value updated for some reason, the above would make it impossible to update the value.

I currently have a module called `Mutable` that has a function `update` that takes the object and property to update and the new value that allows for a value to be updated.

```Elixir
Mutable.update(obj, "some_property", "new_value")
```

Some examples may be if you are dealing with graphics or with DOM elements.
