### ISSUE TITLE
Handling Elixir identifiers with characters that are not allowed in JavaScript identifiers

### ISSUE THREAD

**Issue by bryanjos** [bryanjos/elixirscript#58]
In Elixir you can create variables or function names such as the following:

```elixir
allowed?
allowed!
```

In particular using a `?` or a `!`. And there are some other examples as well. Using `?` or `!` aren't allowed in JavaScript unless you don't use the dot operator

```JavaScript
user.allowed? //Error
user["allowed?"] //Ok
```

Using that syntax with variables isn't an option. In #57, I have done some work so far in calling functions using the bracket notation and updated the stdlib functions with `?` and `!` in them to use the name from Elixir (I was originally omitting the `?` and `!` from the names).

The question is how to handle invalid characters in variable and function names? 

One option is to throw an error when the translator sees a variable or function name with any invalid JavaScript characters.

**Comment by grabbou** [comment]
The most clever solution would've been to rename these methods to something like `user.u1` following reasonable pattern and always use square brackets notation. I would avoid throwing any errors. The compiler should be clever enough to handle all the cases and translate the code in the way it works in the host environment.

**Comment by bryanjos** [comment]
It gets kind of messy. Like what to do with variables? For instance in the case below:

```Elixir
allowed? = true
```

would be translated into something like

```JavaScript
let allowed? = true;
```

Which isn't valid. And then there are function parameters as well. If there is some reasonable pattern to use I'm all for it. Something I would like something that also looks decent if calling it from outside of ElixirScript (i.e. in plain javascript).

**Comment by grabbou** [comment]
Maybe just building a dictionary with all forbidden JS characters yet allowed in Elixir and replacing during conversion would do the trick?

Let's say 

```js
allowed_quote = true
```

> if calling it from outside of ElixirScript (i.e. in plain javascript).
Haven't seen such a use-case in already implemented e.g. `ClojureScript`. I think the main focus should be on implementing as many Elixir features as possible yet keeping the generated code as efficient yet small as possible ;)

**Comment by bryanjos** [comment]
That could definitely work. I'll give it a shot. Thanks!

**Comment by bryanjos** [comment]
Handling it as defined here. `?` becomes `__qmark__` and `!` becomes `__emark__`. The scheme may change in the future but this works for now.
